server:
  port: 8090
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: spring-security-demo
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/security_demo_app
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: false
  mail:
    host: localhost
    port: 1025
    username: welcome
    password: welcome
    from: confirmation@anuj-acadamy.com

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR