version: '1.0'

services:
  api:
    image: 'access-control:latest'
    build:
      context: .
    command:
      - bash -c "docker run -p 1080:1080 -p 1025:1025 maildev/maildev"
    depends_on:
      - db
      - maildev
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/security_demo_app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - 8090:8090
  db:
    image: postgres
    container_name: security-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: security_demo_app

  maildev:
    image: maildev/maildev


