# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install maven
      run: |
        sudo apt-get install maven
        sudo update-ca-certificates -f
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        architecture: x64
        cache: 'maven'

    - name: Setup Cache for Maven packages to speed up build
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Clean And Compile
      run: |
        mvn clean
        mvn compile

    - name: Verify
      run: |
        mvn -B verify

    - name: Build
      run: |
        mvn -B package --file pom.xml
        mkdir staging && cp target/*.jar staging

    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v2
      with:
        name: github-action-artifact
        path: staging

    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - name: "Login to DockerHub"
      uses: docker/login-action@v1
      with:
        password: "${{ secrets.DOCKERHUB_TOKEN }}"
        username: "${{ secrets.DOCKERHUB_USERNAME }}"
    - name: "Push"
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: "."
        file: ./Dockerfile
        push: true
        tags: "anuj7sharma/spring-boot-security:latest"